Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/Applicant_Details__c.object-meta.xml
<CustomObject>
    <label>Applicant Details</label>
    <nameField>
        <displayFormat>APPID-{0000}</displayFormat>
        <label>Applicant Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/Active_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Active_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Applicant active status details</description>
    <label>Active Applicant</label>
    <type>Checkbox</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/Asset_Products__c.field-meta.xml
<CustomField>
    <fullName>Asset_Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Products</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Applicants Details</relationshipLabel>
    <relationshipName>Applicants_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Applicant first name details</description>
    <label>First Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Applicant last name details</description>
    <label>Last Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

PolicyStream_SFDC/force-app-main-default/classes/BatchClassAppStatus.cls
global class BatchClassAppStatus implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('select id, First_Name__c, Last_Name__c,Asset_Products__c, Active_Applicant__c from Applicant_Details__c where Active_Applicant__c = true');
    }
    global void execute(Database.BatchableContext BC, List<Applicant_Details__c> appList){
        if(!appList.isEmpty()){
            for(Applicant_Details__c objApp : appList){
                if(String.isBlank(objApp.Asset_Products__c)){
                    objApp.Active_Applicant__c = false;
                }
            }
            Database.update(appList, false);
        }
    }
    global void finish(Database.BatchableContext BC){
        
    }
}