Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/Applicant_Details__c.object-meta.xml
<CustomObject>
    <label>Applicant Details</label>
    <nameField>
        <displayFormat>APPID-{0000}</displayFormat>
        <label>Applicant Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/Active_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Active_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Applicant active status details</description>
    <label>Active Applicant</label>
    <type>Checkbox</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/Asset_Products__c.field-meta.xml
<CustomField>
    <fullName>Asset_Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Products</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Applicants Details</relationshipLabel>
    <relationshipName>Applicants_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Applicant first name details</description>
    <label>First Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Applicant last name details</description>
    <label>Last Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

PolicyStream_SFDC/force-app-main-default/classes/AppliStatusBatchClass.cls
global class AppliStatusBatchClass implements Database.Batchable<SObject>, Database.Stateful{
    SET<String> successIdSet = new SET<String>();
    SET<String> failedIdSet = new SET<String>();
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('select id, Name, First_Name__c, Last_Name__c, CreatedDate, Active_Applicant__c, Asset_Products__c from Applicant_Details__c where CreatedDate = LAST_MONTH and Active_Applicant__c = true');
    }

    global void execute(Database.BatchableContext BC, List<Applicant_Details__c> appList){
        if(!appList.isEmpty()){
            for(Applicant_Details__c objApp : appList){
                if(String.isBlank(objApp.Asset_Products__c)){
                    objApp.Active_Applicant__c = false;
                }
                Database.SaveResult[] result =  Database.update(appList, false);
                Integer index=0;

                for(Database.SaveResult sr: result){
                    if(sr.isSuccess()){
                        System.debug('Succes = '+appList[index].Name);
                        successIdSet.add(appList[index].Name);
                        index++;
                    }
                    else{
                        System.debug('Failed = '+appList[index].Name);
                        failedIdSet.add(appList[index].Name);
                        index++;
                    }
                    System.debug('Success= '+successIdSet);
                    System.debug('Failed = '+failedIdSet);  
                }
            }
        }
    }
    global void finish(Database.BatchableContext BC){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] {'waradepranav99@gmail.com'});
        mail.setSenderDisplayName('MS Amlin');
        mail.setSubject('Application Status is Updated');
        mail.setPlainTextBody('Success '+successIdSet+'\n Failed= '+failedIdSet);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

    }
}