Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/Applicant_Details__c.object-meta.xml
<CustomObject>
    <label>Applicant Details</label>
    <nameField>
        <displayFormat>APPID-{0000}</displayFormat>
        <label>Applicant Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PolicyStream_SFDC/force-app-main-default/objects/Applicant_Details__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <description>Applicant email id details</description>
    <label>Email Id</label>
    <type>Email</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Applicant first name details</description>
    <label>First Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Applicant last name details</description>
    <label>Last Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <description>Applicant mobile number details</description>
    <label>Mobile Number</label>
    <type>Phone</type>
</CustomField>

PolicyStream_SFDC/force-app-main-default/classes/ApplicationProvider.cls
public with sharing class ApplicationProvider {

    @AuraEnabled 
    public static List<Applicant_Details__c> searchAppAssRecords(Date startDate, Date endDate){
        System.debug('# Received Dates '+startDate+','+endDate);
        try{
            return [select id, Name, First_Name__c, Last_Name__c, Email_Id__c, Mobile_Number__c, Date_of_Birth__c, CreatedDate from Applicant_Details__c where CreatedDate >=:startDate and CreatedDate <=:endDate];
        }
        catch(Exception e) {
            return null;
        }
    }
}