Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/Applicant_Details__c.object-meta.xml
<CustomObject>
    <label>Applicant Details</label>
    <nameField>
        <displayFormat>APPID-{0000}</displayFormat>
        <label>Applicant Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/Active_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Active_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Applicant active status details</description>
    <label>Active Applicant</label>
    <type>Checkbox</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/Asset_Products__c.field-meta.xml
<CustomField>
    <fullName>Asset_Products__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Products</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Applicants Details</relationshipLabel>
    <relationshipName>Applicants_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Applicant first name details</description>
    <label>First Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Insurance Agency Sfdc/force-app-main-default/objects/Applicant_Details__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Applicant last name details</description>
    <label>Last Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

PolicyStream_SFDC/force-app-main-default/classes/TestClassOfAppStatus.cls
@isTest(seeAllData=false)
public class TestClassOfAppStatus{

    @isTest
    public static void testAppBatchMethod(){

        List<Applicant_Details__c> appList = new List<Applicant_Details__c>();
        for(Integer i=1; i<=200; i++){
            Applicant_Details__c objApp = new Applicant_Details__c(First_Name__c='Shankar'+i, Last_Name__c='Pratap'+i, Asset_Products__c= null, Active_Applicant__c = true);
            appList.add(objApp);
        }
        if(!appList.isEmpty()){
            Database.insert(appList, false);
        }
        Test.startTest();
            Database.executeBatch(new BatchClassAppStatus(), 200);
        Test.stopTest();

        List<Applicant_Details__c> actualAppList =[select id, First_Name__c, Last_Name__c, Active_Applicant__c,	Asset_Products__c from Applicant_Details__c where Active_Applicant__c=false];
        System.assertEquals(200, actualAppList.size());
    }
    
}